name: Bug Report
description: File a bug report
title: "bug[optional scope]: <title>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        *Please provide as much detail as possible so we can test and resolve the issue as soon as possible.*

        *The title on this issue uses the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) spec to aid with automation. Please follow the formatting used in the title template.*

  - type: input
    id: chart
    attributes:
      label: Chart
      description: Which helm chart are you using?
      placeholder: helm-chart-test
    validations:
      required: true

  - type: input
    id: chart-version
    attributes:
      label: Chart Version
      description: What version the chart are you using?
      placeholder: ex. 0.1.2
    validations:
      required: true

  - type: input
    id: helm-version
    attributes:
      label: Helm Version
      description: What version of helm are you using?
      placeholder: ex. v3.8.2
    validations:
      required: true

  - type: textarea
    id: k8s-version
    attributes:
      label: Kubernetes Version
      description: What version(s) of kubernetes are you targeting?
      placeholder: ex. 1.22.10
    validations:
      required: true

  - type: dropdown
    id: upgrade
    attributes:
      label: Upgrade?
      description: Did you encounter the issue when upgrading from a previous version of the chart, helm or kubernetes?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: dropdown
    id: encountered-before
    attributes:
      label: Seen the issue elsewhere?
      description: Have you encountered the issue before?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      description: What did you expect to happen?
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual Behaviour?
      description: What actually happened?
      placeholder: Tell us what you saw!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the steps we can take to reproduce the error?
      placeholder: Tell us how to reproduce the error!
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log Data
      description: Please provide any relevant log data.
      placeholder: Redact any secret data from the log before posting.
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Let us know if you have a workaround or know how this can be resolved
      placeholder: Know a solution?
    validations:
      required: false
